Implemented a Contact Page
muhafiz5814/haji-flour-mill pull request #19
Opened 2024-12-19 13:02 UTC by mohamedhesham221

Added a contact form with fields for First Name, Last Name, Email, City (select dropdown), and a Textarea for user messages.
Integrated a Google Map component for location display.
You can configure your location by adding their Google Maps API Key along with Latitude and Longitude in the `Map` component.

2024-12-19 17:20 UTC, muhafiz5814 requested changes
Please make requested changes.

2024-12-19 17:20 UTC, muhafiz5814 commented on frontend/src/pages/main/ContactUs.js
> +  const countries = [
please rename this from `countries` to `cities` here and everywhere it is used in code below.

2024-12-19 17:20 UTC, muhafiz5814 commented on frontend/src/pages/main/ContactUs.js
> +  const [selectedCountry, setSelectedCountry] = useState('');
Please rename `selectedCountry` and `setSelectedCountry` to -> `selectedCity` and `setSelectedCity`.
Also rename from everywhere these are used below in the code.

2024-12-19 17:20 UTC, muhafiz5814 commented on frontend/src/pages/main/ContactUs.js
> +    alert(`Form submitted with input:
remove `is` after first name.
Capitalize first letter of all the field names of this alert message.

2024-12-19 17:20 UTC, muhafiz5814 commented on frontend/src/pages/main/ContactUs.js
> +        <p>Have a question, suggestion, or idea? We’re here to listen and make continuous improvements. Your feedback is valuable in helping us grow and serve you better!.</p>
Please either remove `!` or remove `.`

2024-12-19 17:20 UTC, muhafiz5814 commented on frontend/src/pages/main/ContactUs.js
> +              <label htmlFor="country">Country</label> <span>*</span>
please change label `Country` to `City`.
please change id and htmlFor attribute.

2024-12-19 17:25 UTC, muhafiz5814 commented
@mohamedhesham221

2024-12-19 17:26 UTC, muhafiz5814 commented
@mohamedhesham221 
Also, can you please share screenshot or screen recording of the contact page from your local deployment.

2024-12-19 18:05 UTC, mohamedhesham221 commented
I have implemented the requested changes:

Please note that the map is not rendering correctly on my local setup due to a billing issue with the Google Maps API. You may need to verify the map functionality on your end like your APi key and longitude and latitude.

Let me know if there’s anything else you’d like me to adjust!

https://github.com/user-attachments/assets/515f8de6-2c40-497e-9e21-2fdddfa541b7

2024-12-20 16:07 UTC, muhafiz5814 requested changes
Please go through the changes requested, feel free to clarify any doubt.

2024-12-20 16:07 UTC, muhafiz5814 commented on frontend/src/components/Map.js
Instead of using `@react-google-maps/api` to embed map in website, use a simple HTML `iframe` element, provided by google map itself, to embed a static google map image in website.
It does not require any API key or any credantial.

## Demo

https://github.com/user-attachments/assets/6ce0ef5a-cf7c-4673-a669-bf6c93f78551

As described in the demo video, just copy HTML of any location(I will update it to correct location) and paste it inside Map component in place of `GoogleMap` react element.

Style the page according to it.
If there is any doubt, you can ask.

Don't forget to remove or uninstall `@react-google-maps/api` from project at the end to ensure no unused code/files are left.

@mohamedhesham221

2024-12-20 16:07 UTC, muhafiz5814 commented on frontend/src/pages/main/ContactUs.js
> +  const cites = [
correct the typo `cites` -> `cities` here and everywhere it is used in code below.

2024-12-21 10:57 UTC, mohamedhesham221 commented
I have implemented the requested changes:

https://github.com/user-attachments/assets/bae2963a-4f0a-44f9-a20e-1f308c0af865

@muhafiz5814

2024-12-21 15:37 UTC, muhafiz5814 approved these changes
Great!
Looks like we are good to go now.

2024-12-21 15:54 UTC, merged

2024-12-21 15:58 UTC, muhafiz5814 commented
@mohamedhesham221 
Thanks for contributing to my project.
If you have any suggestion to improve or detect any issue, let me know.
Hoping to get more great contributions.

2024-12-21 17:30 UTC, mohamedhesham221 commented
Glad to contribute! I'll let you know if I spot any improvements or issues. Looking forward to future collaborations!